id: PF9D94CA8
initial_creation_type: input
source_metadata:
  Title: Tattvaratnāvalokaḥ
  Editor: Pandey, Janardan
  Publisher: Central Institute of Higher Tibetan Studies
  Place of Publication: Sarnath
  Year: '1997'
  Tattvaratnāvalokaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2004'
    Proof Reader: Milan Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:59:02.575246'
last_modified_at: '2022-03-08T16:59:02.575254'
